import type { Reminder } from '../types';

export const MOCK_REMINDERS: Reminder[] = [
  {
    id: '1',
    title: 'Prepare Q3 report',
    description: 'Board meeting next week. Finance numbers needed by Friday.',
    priority: 'high',
    labels: ['work', 'urgent'],
    dueTime: new Date(Date.now() + 4 * 3600000).toISOString(),
    transcript: 'You discussed this in yesterday\'s standup. Sarah needs marketing numbers. Tom has engineering KPIs.',
    context: 'Extracted from voice notes at 9:42 AM and 2:15 PM yesterday',
    sourceTime: new Date(Date.now() - 86400000).toISOString(),
    isNew: false,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    archivedAt: null,
  },
  {
    id: '2',
    title: 'Call dentist',
    description: 'Follow-up scheduled last week. Office hours 9 AM - 5 PM.',
    priority: 'medium',
    labels: ['health', 'personal'],
    dueTime: new Date(Date.now() + 3 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    archivedAt: null,
  },
  {
    id: '3',
    title: 'Design review with UX team',
    description: '30 min sync. New onboarding flow mockups.',
    priority: 'medium',
    labels: ['meeting', 'work'],
    dueTime: new Date(Date.now() + 26 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    archivedAt: null,
  },
  {
    id: '4',
    title: 'Research standing desk',
    description: 'Herman Miller recommended for back pain.',
    priority: 'low',
    labels: ['personal'],
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    archivedAt: null,
  },
  {
    id: '5',
    title: 'Review contract draft',
    description: 'Legal sent the NDA for the Acme deal. Needs sign-off before Thursday.',
    priority: 'high',
    labels: ['work', 'urgent'],
    dueTime: new Date(Date.now() + 48 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    archivedAt: null,
  },
  {
    id: '6',
    title: 'Investor update — April',
    description: 'Send the monthly update. Template is in Notion under "IR."',
    priority: 'low',
    labels: ['finance', 'work'],
    dueTime: new Date(Date.now() + 96 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    archivedAt: null,
  },
];
