# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VADServiceStub(object):
    """============================================================
    VAD Service — detects speech in audio stream
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectSpeech = channel.stream_stream(
                '/inference.VADService/DetectSpeech',
                request_serializer=inference__pb2.AudioChunk.SerializeToString,
                response_deserializer=inference__pb2.VADResult.FromString,
                _registered_method=True)


class VADServiceServicer(object):
    """============================================================
    VAD Service — detects speech in audio stream
    ============================================================
    """

    def DetectSpeech(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VADServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectSpeech': grpc.stream_stream_rpc_method_handler(
                    servicer.DetectSpeech,
                    request_deserializer=inference__pb2.AudioChunk.FromString,
                    response_serializer=inference__pb2.VADResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.VADService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.VADService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VADService(object):
    """============================================================
    VAD Service — detects speech in audio stream
    ============================================================
    """

    @staticmethod
    def DetectSpeech(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/inference.VADService/DetectSpeech',
            inference__pb2.AudioChunk.SerializeToString,
            inference__pb2.VADResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ASRServiceStub(object):
    """============================================================
    ASR Service — streaming speech recognition
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamRecognize = channel.stream_stream(
                '/inference.ASRService/StreamRecognize',
                request_serializer=inference__pb2.AudioChunk.SerializeToString,
                response_deserializer=inference__pb2.RecognizeResult.FromString,
                _registered_method=True)
        self.RecognizeFile = channel.unary_unary(
                '/inference.ASRService/RecognizeFile',
                request_serializer=inference__pb2.RecognizeFileRequest.SerializeToString,
                response_deserializer=inference__pb2.RecognizeFileResponse.FromString,
                _registered_method=True)


class ASRServiceServicer(object):
    """============================================================
    ASR Service — streaming speech recognition
    ============================================================
    """

    def StreamRecognize(self, request_iterator, context):
        """Bidirectional streaming: client sends audio, server streams results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeFile(self, request, context):
        """Unary: send entire audio file, get full transcription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ASRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamRecognize': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamRecognize,
                    request_deserializer=inference__pb2.AudioChunk.FromString,
                    response_serializer=inference__pb2.RecognizeResult.SerializeToString,
            ),
            'RecognizeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFile,
                    request_deserializer=inference__pb2.RecognizeFileRequest.FromString,
                    response_serializer=inference__pb2.RecognizeFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.ASRService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.ASRService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ASRService(object):
    """============================================================
    ASR Service — streaming speech recognition
    ============================================================
    """

    @staticmethod
    def StreamRecognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/inference.ASRService/StreamRecognize',
            inference__pb2.AudioChunk.SerializeToString,
            inference__pb2.RecognizeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.ASRService/RecognizeFile',
            inference__pb2.RecognizeFileRequest.SerializeToString,
            inference__pb2.RecognizeFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SpeakerServiceStub(object):
    """============================================================
    Speaker Service — speaker embedding and verification
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractEmbedding = channel.unary_unary(
                '/inference.SpeakerService/ExtractEmbedding',
                request_serializer=inference__pb2.ExtractEmbeddingRequest.SerializeToString,
                response_deserializer=inference__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.VerifySpeaker = channel.unary_unary(
                '/inference.SpeakerService/VerifySpeaker',
                request_serializer=inference__pb2.VerifySpeakerRequest.SerializeToString,
                response_deserializer=inference__pb2.VerifySpeakerResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/inference.SpeakerService/HealthCheck',
                request_serializer=inference__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=inference__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class SpeakerServiceServicer(object):
    """============================================================
    Speaker Service — speaker embedding and verification
    ============================================================
    """

    def ExtractEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifySpeaker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeakerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractEmbedding,
                    request_deserializer=inference__pb2.ExtractEmbeddingRequest.FromString,
                    response_serializer=inference__pb2.EmbeddingResponse.SerializeToString,
            ),
            'VerifySpeaker': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifySpeaker,
                    request_deserializer=inference__pb2.VerifySpeakerRequest.FromString,
                    response_serializer=inference__pb2.VerifySpeakerResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=inference__pb2.HealthCheckRequest.FromString,
                    response_serializer=inference__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.SpeakerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.SpeakerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeakerService(object):
    """============================================================
    Speaker Service — speaker embedding and verification
    ============================================================
    """

    @staticmethod
    def ExtractEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.SpeakerService/ExtractEmbedding',
            inference__pb2.ExtractEmbeddingRequest.SerializeToString,
            inference__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifySpeaker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.SpeakerService/VerifySpeaker',
            inference__pb2.VerifySpeakerRequest.SerializeToString,
            inference__pb2.VerifySpeakerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.SpeakerService/HealthCheck',
            inference__pb2.HealthCheckRequest.SerializeToString,
            inference__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
